
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/foodmanagement?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #监控统计拦截的filters
    filters: stat,wall,log4j
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSC                                                                                                        ache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000

  redis:
    host: 127.0.0.1
    port: 6379

  google:
    keyFileLocation: google/fast-fire-302206-d09f05a462ba.json
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
    time-zone: GMT+8
server:
  port: 2026
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.design.foodmanagement.pojo
  configuration:
    map-underscore-to-camel-case: true
